### ISSUE TITLE
DH - Issues SPELLS/TALENTS

### ISSUE THREAD

**Issue by browller** [BFASource/BFACore#2]
--Talents--
>Havoc:

- On TALENT spellid = 203550
> It increases the Eye Beam timer, but fury regen effect doesn't work 

- On TALENT spellid= 258881
> The effect is triggering with all abilities instead only trigger on final of Blade Dance (188499)

- On TALENT spellid = 206477
> It works, but when CHAOS NOVA is used, the talent give 30 Fury Resource to DH (it should remove CHAOS NOVA fury costs and descreases cd only)

- On TALENT spellid = 213410
> If DH is already on METAMORPHOSIS effect, the timer doesn't increase + 8 sec to the effect.

-On TALENT spellid = 204909
> Leech effect doesn't work

--Spells--
>Havoc:

- On SPELL = 162794
>The chance to refund FURY doesn't work, it never refunds.

- On SPELL = 195449
>Dazed effect affects players too, it should target only enemies and Leech effect doesn't work.

- On SPELL = 195440
>The chance to generate a Soul Fragment doesn't work

- On SPELL = 195441
>the ricochet effect doesn't work, it target only 1 enemy

-On SPELL = 198013
>If move when cast, the effect stop working.

**Comment by cooler-SAI** [comment]
thanks for report. we really need help here)
