### ISSUE TITLE
spell_area : autocast

### ISSUE THREAD

**Issue by firelook** [BFASource/BFACore#4]
**Description:**

spell_area : autocast field doesn't exist

**Current behaviour:**

2019_04_26_00_world.sql script can not load because it makes an insert with that columns

**Expected behaviour:**

no alter table found for autocast

**Steps to reproduce the problem:**
started with a clean database 
apply 
BFADB_world_801.02.sql
then all updates and hangs

**Comment by ReyDonovan** [comment]
autocast -> flags

**Comment by yudian1994** [comment]
the code is not compatible with the database and the world server does not start

**Comment by cooler-SAI** [comment]
no need for master branch
https://trinitycore.atlassian.net/wiki/spaces/tc/pages/2130105/spell+area
