### ISSUE TITLE
The warrior when using execute, crashing the server of the world, spell id 163201

### ISSUE THREAD

**Issue by remamakiller** [BFASource/BFACore#7]
**Description:**

CHANGEME Description of the problem or issue here.

**Current behaviour:**

CHANGEME Tell us what happens.
If this is a crash, post the crashlog (upload to https://gist.github.com/).

**Expected behaviour:**

CHANGEME Tell us what should happen instead.

**Steps to reproduce the problem:**

1. CHANGEME Step 1 include entries of affected creatures / items / quests with a link to the relevant wowhead page.  
2. Step 2
3. Step 3

**Branch(es):**

CHANGEME 3.3.5, master or both

**TC rev. hash/commit:** 

CHANGEME Copy the result of server debug command (if you need to run it from client get prat addon)

**Operating system:** CHANGEME OS

**Comment by Nupper** [comment]
please fill out the description better...but i can confirm execute crashes server

**Comment by remamakiller** [comment]
When I want to attack with the spell, execute, I close the world

**Comment by remamakiller** [comment]
Not knowing English, I'm using the Google Chrome translator
Apologies

**Comment by remamakiller** [comment]
<a href='https://postimg.cc/pprJTWc4' target='_blank'><img src='https://i.postimg.cc/pprJTWc4/spell.jpg' border='0' alt='spell'/></a>
